### PR TITLE
Update main.lua

### PR DESCRIPTION
**Pull request by hasidu**
- Added players can add an image for vehicle
- Removed fuel export and t1ger key export
- Added infinite vehicles spawn option just look on comments line 103
- Look on line 16 to edit radius of TEXT UI

### CODE REVIEW

**Comment by AfterLifeStudio** [comment]
but it will spawn multiple vehicle with same numberplate

**Comment by hasidu** [comment]
yes

the problem is if the vehicle will destroy or something you need to restart the server to spawn that vehicle

**Comment by AfterLifeStudio** [comment]
can add an option to get the vehicle back in the garage

**Comment by hasidu** [comment]
> can add an option to get the vehicle back in the garage

yeah it will be better

**Pull request closed without merging**
